apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: eW91cnBhc3N3b3Jk # Base64 encoded 'yourpassword'
  mysql-database: Y29tbWVudHM= # Base64 encoded 'comments'
