name: GoLint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install golangci-lint
        run: go get github.com/golangci/golangci-lint/cmd/golangci-lint

      - name: Run golangci-lint
        run: golangci-lint run
